SET(ORDINALS
  ORDINAL_INT
  ORDINAL_INT32_T
  ORDINAL_INT64_T
  ORDINAL_UINT32_T
  ORDINAL_UINT64_T
)
SET(ORDINAL_INT_CPP_TYPE int)
SET(ORDINAL_INT32_T_CPP_TYPE int32_t)
SET(ORDINAL_INT64_T_CPP_TYPE int64_t)
SET(ORDINAL_UINT32_T_CPP_TYPE uint32_t)
SET(ORDINAL_UINT64_T_CPP_TYPE uint64_t)

SET(DIVERG_INST_ORDINAL_INT_DEFAULT ${DIVERG_ADD_DEFAULT_ETI})
SET(DIVERG_INST_ORDINAL_INT32_T_DEFAULT ${DIVERG_ADD_DEFAULT_ETI})
SET(DIVERG_INST_ORDINAL_UINT32_T_DEFAULT ${DIVERG_ADD_DEFAULT_ETI})
SET(DIVERG_INST_ORDINAL_INT64_T_DEFAULT  OFF)
SET(DIVERG_INST_ORDINAL_UINT64_T_DEFAULT  OFF)


DIVERG_ADD_OPTION(
  INST_ORDINAL_INT
  ${DIVERG_INST_ORDINAL_INT_DEFAULT}
  BOOL
  "Whether to pre instantiate kernels for the ordinal type int.  This option is DiverG_INST_ORDINAL_INT=ON by default. Default: ON"
  )

DIVERG_ADD_OPTION(
  INST_ORDINAL_INT32_T
  ${DIVERG_INST_ORDINAL_INT32_T_DEFAULT}
  BOOL
  "Whether to pre instantiate kernels for the ordinal type int32_t.  This option is DiverG_INST_ORDINAL_INT32_T=ON by default. Default: ON"
  )

DIVERG_ADD_OPTION(
  INST_ORDINAL_UINT32_T
  ${DIVERG_INST_ORDINAL_UINT32_T_DEFAULT}
  BOOL
  "Whether to pre instantiate kernels for the ordinal type uint32_t.  This option is DiverG_INST_ORDINAL_UINT32_T=ON by default. Default: ON"
  )

DIVERG_ADD_OPTION(
  INST_ORDINAL_INT64_T
  ${DIVERG_INST_ORDINAL_INT64_T_DEFAULT}
  BOOL
  "Whether to pre instantiate kernels for the ordinal type int64_t.  This option is DiverG_INST_ORDINAL_INT64_T=OFF by default. Default: OFF"
  )

DIVERG_ADD_OPTION(
  INST_ORDINAL_UINT64_T
  ${DIVERG_INST_ORDINAL_UINT64_T_DEFAULT}
  BOOL
  "Whether to pre instantiate kernels for the ordinal type uint64_t.  This option is DiverG_INST_ORDINAL_UINT64_T=OFF by default. Default: OFF"
  )

IF (DIVERG_INST_ORDINAL_INT)
  LIST(APPEND ORDINAL_LIST "int")
ENDIF()

IF (DIVERG_INST_ORDINAL_INT32_T)
  LIST(APPEND ORDINAL_LIST "int32_t")
ENDIF()

IF (DIVERG_INST_ORDINAL_UINT32_T)
  LIST(APPEND ORDINAL_LIST "uint32_t")
ENDIF()

IF (DIVERG_INST_ORDINAL_INT64_T)
  LIST(APPEND ORDINAL_LIST "int64_t")
ENDIF()

IF (DIVERG_INST_ORDINAL_UINT64_T)
  LIST(APPEND ORDINAL_LIST "uint64_t")
ENDIF()
